from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor

from datetime import datetime, date , timedelta
import os

from collections import defaultdict

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#0B6E4F")

heading_style = styles["Heading2"]

normal_style = styles["BodyText"]

from datetime import date, timedelta

def generate_daily_pdf(report_data):

    # -----------------------------
    # Read all report data
    # -----------------------------

    logo = Image(
        "logo/sunfra_logo.png",
        width=0.9 * inch,
        height=0.9 * inch
    )

    report_date = report_data["report_date"]
    production_records = report_data["production_records"]
    feed_records = report_data["feed_records"]
    medicine_records = report_data["medicine_records"]
    production_totals = report_data["production_totals"]
    feed_totals = report_data["feed_totals"]
    medicine_totals = report_data["medicine_totals"]
    pending_reports = report_data["pending_reports"]

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/Sunfra_Farm_Report_{report_date}.pdf"

    doc = SimpleDocTemplate(
        filename,
        rightMargin=25,
        leftMargin=25,
        topMargin=25,
        bottomMargin=25,
    )

    elements = []

    # =====================================================
    # HEADER
    # =====================================================

    title = Paragraph(
        """
        <font size="22" color="#0B6E4F">
        <b>SUNFRA FARM</b>
        </font><br/>
        <font size="13">
        Daily Farm Report
        </font>
        """,
        title_style,
    )

    header = Table(
        [[logo, title]],
        colWidths=[80, 420]
    )

    header.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ])
    )

    elements.append(header)

    elements.append(Spacer(1, 15))

    generated_time = datetime.now().strftime("%d-%b-%Y %I:%M %p")

    info = [
        ["Report Date", report_date],
        ["Generated At", generated_time],
        ["Generated By", "Farm AI Assistant"],
    ]

    info_table = Table(
        info,
        colWidths=[120, 300],
    )

    info_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E8F5E9")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(info_table)

    elements.append(Spacer(1, 20))

    # =====================================================
    # =====================================================
    # PRODUCTION SUMMARY
    # =====================================================

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Production Summary</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    table_data = [
        [
            "Shed",
            "Birds",
            "Mortality",
            "Produced",
            "Broken",
            "Sold",
            "Stock",
        ]
    ]

    for record in production_records:

        birds = record.birds or 0
        mortality = record.mortality or 0
        produced = record.produced or 0
        broken = record.broken or 0
        sold = record.sold or 0

        stock = produced - broken - sold

        table_data.append([
            record.shed_no,
            birds,
            mortality,
            produced,
            broken,
            sold,
            stock,
        ])

    production_table = Table(
        table_data,
        colWidths=[45, 55, 60, 65, 55, 55, 60],
    )

    production_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#0B6E4F")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

            ("BACKGROUND", (0, 1), (-1, -1), HexColor("#F8F8F8")),
        ])
    )

    elements.append(production_table)

    elements.append(Spacer(1, 18))

    # =====================================================
    # FARM TOTALS
    # =====================================================

    total_birds = 0
    total_mortality = 0
    total_produced = 0
    total_broken = 0
    total_sold = 0

    for record in production_records:

        total_birds += record.birds or 0
        total_mortality += record.mortality or 0
        total_produced += record.produced or 0
        total_broken += record.broken or 0
        total_sold += record.sold or 0

    current_stock = total_produced - total_broken - total_sold

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Farm Totals</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    totals = [

        ["Total Birds", total_birds],

        ["Total Mortality", total_mortality],

        ["Total Produced", total_produced],

        ["Total Broken", total_broken],

        ["Total Sold", total_sold],

        ["Current Stock", current_stock],

    ]

    totals_table = Table(
        totals,
        colWidths=[180, 120],
    )

    totals_table.setStyle(
        TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E8F5E9")),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ])
    )

    elements.append(totals_table)

    elements.append(Spacer(1, 18))

    # =====================================================
    # FEED INVENTORY
    # =====================================================

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Feed Inventory</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    feed_table_data = [

        [
            "Shed",
            "Feed",
            "Available",
            "Used",
            "Remaining",
        ]

    ]

    for feed in feed_records:

        available = feed.available or 0
        used = feed.used or 0
        remaining = available - used

        feed_table_data.append([

            feed.shed_no,

            feed.feed_name,

            f"{available} {feed.unit}",

            f"{used} {feed.unit}",

            f"{remaining} {feed.unit}",

        ])

    feed_table = Table(

        feed_table_data,

        colWidths=[50, 170, 80, 70, 90]

    )

    feed_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#2E7D32")),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

            ("BACKGROUND", (0, 1), (-1, -1), HexColor("#F8FFF8"))

        ])

    )

    elements.append(feed_table)

    elements.append(Spacer(1, 10))

    available, used, remaining = feed_totals

    feed_total_table = Table(   

        [

            ["Total Available", f"{available} kg"],

            ["Total Used", f"{used} kg"],

            ["Total Remaining", f"{remaining} kg"],

        ],

        colWidths=[180, 120],

    )

    feed_total_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E8F5E9")),

            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ])

    )

    elements.append(feed_total_table)

    elements.append(Spacer(1, 18))

    # =====================================================
    # MEDICINE INVENTORY
    # =====================================================

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Medicine Inventory</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    medicine_table_data = [

        [
            "Shed",
            "Medicine",
            "Available",
            "Used",
            "Remaining",
        ]

    ]

    for medicine in medicine_records:

        available = medicine.available or 0
        used = medicine.used or 0
        remaining = available - used

        medicine_table_data.append([

            medicine.shed_no,

            medicine.medicine_name,

            f"{available} {medicine.unit}",

            f"{used} {medicine.unit}",

            f"{remaining} {medicine.unit}",

        ])

    medicine_table = Table(

        medicine_table_data,

        colWidths=[50, 170, 80, 70, 90]

    )

    medicine_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1565C0")),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

            ("BACKGROUND", (0, 1), (-1, -1), HexColor("#F4F8FF"))

        ])

    )

    elements.append(medicine_table)

    elements.append(Spacer(1, 10))

    available, used, remaining = medicine_totals

    medicine_total_table = Table(

        [

            ["Total Available", f"{available} kg"],

            ["Total Used", f"{used} kg"],

            ["Total Remaining", f"{remaining} kg"],

        ],

        colWidths=[180, 120],

    )

    medicine_total_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E3F2FD")),

            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ])

    )

    elements.append(medicine_total_table)

    elements.append(Spacer(1, 18))

    # =====================================================
    # PENDING REPORTS
    # =====================================================

    elements.append(
        Paragraph(
            "<b><font size=14 color='#D32F2F'>Pending Reports</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    if pending_reports:

        pending_table = [["Shed", "Missing Fields"]]

        for report in pending_reports:

            pending_table.append([
                report["shed"],
                ", ".join(report["missing"])
            ])

        table = Table(
            pending_table,
            colWidths=[70, 320]
        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#D32F2F")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

            ])

        )

        elements.append(table)

    else:

        elements.append(

            Paragraph(

                "✅ All sheds have submitted complete reports.",

                normal_style,

            )

        )

        elements.append(Spacer(1, 18))

        elements.append(
        Paragraph(
            "<font color='grey'>Generated automatically by Sunfra Farm AI Assistant</font>",
            normal_style,
        )
    )

    elements.append(
        Paragraph(
            "<font color='grey'>Confidential - Internal Farm Report</font>",
            normal_style,
        )
    )

    doc.build(elements)

    return filename

from database import (
    get_daily_summary,
    get_weekly_summary,
    get_monthly_summary ,

    get_all_feeds,
    get_all_medicines,
    get_feed_totals_kg,
    get_medicine_totals_kg,
    get_missing_fields , 
     
    get_monthly_feeds , 
    get_shed_daily_summary , 

    get_shed_daily_summary,
    get_shed_weekly_summary,
    get_shed_monthly_summary,

    get_day_comparison,
    get_week_comparison ,
    get_month_comparison , 
    get_day_comparison_between_dates
)

def generate_daily_pdf_report(report_date):

    production_records = get_daily_summary(report_date)

    feed_records = get_all_feeds(report_date)

    medicine_records = get_all_medicines()

    feed_totals = get_feed_totals_kg()

    medicine_totals = get_medicine_totals_kg()

    pending = []

    missing = get_missing_fields(report_date)

    for shed, fields in missing.items():

        pending.append({

            "shed": shed,

            "missing": fields

        })

    report_data = {

        "report_date": report_date,

        "production_records": production_records,

        "feed_records": feed_records,

        "medicine_records": medicine_records,

        "production_totals": {},

        "feed_totals": feed_totals,

        "medicine_totals": medicine_totals,

        "pending_reports": pending,

    }

    return generate_daily_pdf(report_data)

def generate_weekly_pdf_report(period):

    production_records = get_weekly_summary(period)

    today = date.today()

    if period == "last_week":

        this_week_start = today - timedelta(days=today.weekday())

        start_date = this_week_start - timedelta(days=7)

        end_date = this_week_start - timedelta(days=1)

        report_title = "Last Week"

    else:

        start_date = today - timedelta(days=today.weekday())

        end_date = today

        report_title = "This Week"

    # Fetch feed records for the selected week
    feed_records = get_all_feeds(start_date, end_date)

    medicine_records = get_all_medicines()

    feed_totals = get_feed_totals_kg()

    medicine_totals = get_medicine_totals_kg()

    report_data = {

        "report_date": report_title,

        "production_records": production_records,

        "feed_records": feed_records,

        "medicine_records": medicine_records,

        "production_totals": {},

        "feed_totals": feed_totals,

        "medicine_totals": medicine_totals,

        "pending_reports": []

    }

    return generate_weekly_pdf(report_data)

def generate_weekly_pdf(report_data):

    # -----------------------------
    # Read all report data
    # -----------------------------

    logo = Image(
        "logo/sunfra_logo.png",
        width=0.9 * inch,
        height=0.9 * inch
    )

    report_date = report_data["report_date"]
    production_records = report_data["production_records"]
    feed_records = report_data["feed_records"]
    medicine_records = report_data["medicine_records"]
    production_totals = report_data["production_totals"]
    feed_totals = report_data["feed_totals"]
    medicine_totals = report_data["medicine_totals"]
    pending_reports = report_data["pending_reports"]

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/Sunfra_Farm_Report_{report_date}.pdf"

    doc = SimpleDocTemplate(
        filename,
        rightMargin=25,
        leftMargin=25,
        topMargin=25,
        bottomMargin=25,
    )

    elements = []

    # =====================================================
    # HEADER
    # =====================================================

    title = Paragraph(
        """
        <font size="22" color="#0B6E4F">
        <b>SUNFRA FARM</b>
        </font><br/>
        <font size="13">
        Weekly Farm Report
        </font>
        """,
        title_style,
    )

    header = Table(
        [[logo, title]],
        colWidths=[80, 420]
    )

    header.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ])
    )

    elements.append(header)

    elements.append(Spacer(1, 15))

    generated_time = datetime.now().strftime("%d-%b-%Y %I:%M %p")

    info = [
        ["Report Date", report_date],
        ["Generated At", generated_time],
        ["Generated By", "Farm AI Assistant"],
    ]

    info_table = Table(
        info,
        colWidths=[120, 300],
    )

    info_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E8F5E9")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(info_table)

    elements.append(Spacer(1, 20))

    # =====================================================
    # PRODUCTION SUMMARY
    # =====================================================

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Production Summary</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1,8))

    grouped = defaultdict(list)

    for r in production_records:
        grouped[r.date].append(r)

    for report_day in sorted(grouped.keys()):

        elements.append(
            Paragraph(
                f"<b>Date : {report_day}</b>",
                normal_style
            )
        )

        elements.append(Spacer(1,5))

        table_data = [[
            "Shed",
            "Birds",
            "Mortality",
            "Produced",
            "Broken",
            "Sold",
            "Stock"
        ]]

        for r in grouped[report_day]:

            produced = r.produced or 0
            broken = r.broken or 0
            sold = r.sold or 0

            stock = produced - broken - sold

            table_data.append([
                r.shed_no,
                r.birds or 0,
                r.mortality or 0,
                produced,
                broken,
                sold,
                stock
            ])

        production_table = Table(
            table_data,
            colWidths=[45,55,60,65,55,55,60]
        )

        production_table.setStyle(
            TableStyle([
                ("BACKGROUND",(0,0),(-1,0),HexColor("#0B6E4F")),
                ("TEXTCOLOR",(0,0),(-1,0),colors.white),
                ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
                ("GRID",(0,0),(-1,-1),0.5,colors.grey),
                ("ALIGN",(0,0),(-1,-1),"CENTER"),
                ("BOTTOMPADDING",(0,0),(-1,0),10),
                ("BACKGROUND",(0,1),(-1,-1),HexColor("#F8F8F8")),
            ])
        )

        elements.append(production_table)

        elements.append(Spacer(1,12))

    # =====================================================
    # FARM TOTALS
    # =====================================================

    total_birds = 0
    total_mortality = 0
    total_produced = 0
    total_broken = 0
    total_sold = 0

    for record in production_records:

        total_birds += record.birds or 0
        total_mortality += record.mortality or 0
        total_produced += record.produced or 0
        total_broken += record.broken or 0
        total_sold += record.sold or 0

    current_stock = total_produced - total_broken - total_sold

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Farm Totals</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    totals = [

        ["Total Birds", total_birds],

        ["Total Mortality", total_mortality],

        ["Total Produced", total_produced],

        ["Total Broken", total_broken],

        ["Total Sold", total_sold],

        ["Current Stock", current_stock],

    ]

    totals_table = Table(
        totals,
        colWidths=[180, 120],
    )

    totals_table.setStyle(
        TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E8F5E9")),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ])
    )

    elements.append(totals_table)

    elements.append(Spacer(1, 18))

    # =====================================================
    # FEED INVENTORY
    # =====================================================

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Feed Inventory</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    feeds_by_date = defaultdict(list)

    for feed in feed_records:
        feeds_by_date[feed.date].append(feed)

    for feed_date in sorted(feeds_by_date.keys()):

        elements.append(
            Paragraph(
                f"<b>Date : {feed_date}</b>",
                normal_style
            )
        )

        elements.append(Spacer(1,5))

        table_data = [[
            "Shed",
            "Feed",
            "Available",
            "Used",
            "Remaining"
        ]]

        for feed in feeds_by_date[feed_date]:

            available = feed.available or 0
            used = feed.used or 0
            remaining = available - used

            table_data.append([
                feed.shed_no,
                feed.feed_name,
                f"{available} {feed.unit}",
                f"{used} {feed.unit}",
                f"{remaining} {feed.unit}",
            ])

        table = Table(
            table_data,
            colWidths=[50,170,80,70,90]
        )

        table.setStyle(
            TableStyle([
                ("BACKGROUND",(0,0),(-1,0),HexColor("#2E7D32")),
                ("TEXTCOLOR",(0,0),(-1,0),colors.white),
                ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
                ("GRID",(0,0),(-1,-1),0.5,colors.grey),
                ("ALIGN",(0,0),(-1,-1),"CENTER"),
                ("BOTTOMPADDING",(0,0),(-1,0),8),
                ("BACKGROUND",(0,1),(-1,-1),HexColor("#F8FFF8"))
            ])
        )

        elements.append(table)

        elements.append(Spacer(1,12))

    elements.append(Spacer(1, 10))

    elements.append(
            Paragraph(
                "<b><font size=14 color='#0B6E4F'>Current Feed Inventory</font></b>",
                heading_style,
            )
    )

    available, used, remaining = feed_totals

    feed_total_table = Table(   

        [

            ["Total Available", f"{available} kg"],

            ["Total Used", f"{used} kg"],

            ["Total Remaining", f"{remaining} kg"],

        ],

        colWidths=[180, 120],

    )

    feed_total_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E8F5E9")),

            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ])

    )

    elements.append(feed_total_table)

    elements.append(Spacer(1, 18))

    # =====================================================
    # MEDICINE INVENTORY
    # =====================================================

    elements.append(
        Paragraph(
            "<b><font size=14 color='#0B6E4F'>Current Medicine Inventory</font></b>",
            heading_style,
        )
    )

    elements.append(Spacer(1, 8))

    medicine_table_data = [

        [
            "Shed",
            "Medicine",
            "Available",
            "Used",
            "Remaining",
        ]

    ]

    for medicine in medicine_records:

        available = medicine.available or 0
        used = medicine.used or 0
        remaining = available - used

        medicine_table_data.append([

            medicine.shed_no,

            medicine.medicine_name,

            f"{available} {medicine.unit}",

            f"{used} {medicine.unit}",

            f"{remaining} {medicine.unit}",

        ])

    medicine_table = Table(

        medicine_table_data,

        colWidths=[50, 170, 80, 70, 90]

    )

    medicine_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1565C0")),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

            ("BACKGROUND", (0, 1), (-1, -1), HexColor("#F4F8FF"))

        ])

    )

    elements.append(medicine_table)

    elements.append(Spacer(1, 10))

    available, used, remaining = medicine_totals

    medicine_total_table = Table(

        [

            ["Total Available", f"{available} kg"],

            ["Total Used", f"{used} kg"],

            ["Total Remaining", f"{remaining} kg"],

        ],

        colWidths=[180, 120],

    )

    medicine_total_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), HexColor("#E3F2FD")),

            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ])

    )

    elements.append(medicine_total_table)

    elements.append(Spacer(1, 18))

    elements.append(
        Paragraph(
            "<font color='grey'>Generated automatically by Sunfra Farm AI Assistant</font>",
            normal_style,
        )
    )

    elements.append(
        Paragraph(
            "<font color='grey'>Confidential - Internal Farm Report</font>",
            normal_style,
        )
    )

    doc.build(elements)

    return filename

def generate_monthly_pdf_report(period):

    production_records = get_monthly_summary(period)

    if period == "last_month":
        report_title = "Last Month"
    else:
        report_title = "This Month"

    # Fetch feed records for the selected week
    feed_records = get_monthly_feeds(period)

    medicine_records = get_all_medicines()

    feed_totals = get_feed_totals_kg()

    medicine_totals = get_medicine_totals_kg()

    report_data = {

        "report_date": report_title,

        "production_records": production_records,

        "feed_records": feed_records,

        "medicine_records": medicine_records,

        "production_totals": {},

        "feed_totals": feed_totals,

        "medicine_totals": medicine_totals,

        "pending_reports": []

    }

    return generate_weekly_pdf(report_data)

def generate_shed_pdf_report(shed_no, period):

    if period == "today":

        report_date = date.today().strftime("%Y-%m-%d")

        record = get_shed_daily_summary(
            report_date,
            shed_no
        )

        production_records = []

        if record:
            production_records.append(record)

        feed_records = get_all_feeds(
            report_date,
            shed_no=shed_no
        )

        report_title = f"Today's Shed {shed_no} Report"

    elif period in ["this_week", "last_week"]:

        production_records = get_shed_weekly_summary(
            period,
            shed_no
        )

        today = date.today()

        if period == "last_week":

            this_week_start = today - timedelta(days=today.weekday())

            start_date = this_week_start - timedelta(days=7)

            end_date = this_week_start - timedelta(days=1)

            report_title = f"Last Week Shed {shed_no} Report"

        else:

            start_date = today - timedelta(days=today.weekday())

            end_date = today

            report_title = f"This Week Shed {shed_no} Report"

        feed_records = get_all_feeds(
            start_date,
            end_date,
            shed_no
        )

    elif period in ["this_month", "last_month"]:

        production_records = get_shed_monthly_summary(
            period,
            shed_no
        )

        today = date.today()

        if period == "last_month":

            first_day = today.replace(day=1)

            end_date = first_day - timedelta(days=1)

            start_date = end_date.replace(day=1)

            report_title = f"Last Month Shed {shed_no} Report"

        else:

            start_date = today.replace(day=1)

            end_date = today

            report_title = f"This Month Shed {shed_no} Report"

        feed_records = get_all_feeds(
            start_date,
            end_date,
            shed_no
        )

    medicine_records = get_all_medicines()

    feed_totals = get_feed_totals_kg()

    medicine_totals = get_medicine_totals_kg()

    report_data = {

        "report_date": report_title,

        "production_records": production_records,

        "feed_records": feed_records,

        "medicine_records": medicine_records,

        "production_totals": {},

        "feed_totals": feed_totals,

        "medicine_totals": medicine_totals,

        "pending_reports": []

    }

    return generate_weekly_pdf(report_data)

def generate_comparison_pdf(report_data):

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/Comparison_Report_{report_data['title'].replace(' ', '_')}.pdf"

    doc = SimpleDocTemplate(
        filename,
        rightMargin=25,
        leftMargin=25,
        topMargin=25,
        bottomMargin=25,
    )

    elements = []

    # -----------------------------------
    # Title
    # -----------------------------------

    title = Paragraph(
        f"""
        <font size="22" color="#0B6E4F">
        <b>SUNFRA FARM</b>
        </font><br/>
        <font size="15">
        Comparison Report
        </font><br/><br/>
        <font size="12">
        {report_data['title']}
        </font>
        """,
        title_style
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    if report_data["shed"] is not None:

        elements.append(
            Paragraph(
                f"<b>Shed :</b> {report_data['shed']}",
                normal_style
            )
        )

        elements.append(Spacer(1, 10))

    current = report_data["current"]
    previous = report_data["previous"]

    table_data = [
        [
            "Metric",
            "Current",
            "Previous",
            "Difference"
        ]
    ]

    metrics = [
        ("Produced Eggs", "produced"),
        ("Broken Eggs", "broken"),
        ("Sold Eggs", "sold"),
        ("Mortality", "mortality"),
        ("Birds", "birds")
    ]

    for label, key in metrics:

        current_value = current[key]
        previous_value = previous[key]

        difference = current_value - previous_value

        table_data.append([
            label,
            current_value,
            previous_value,
            difference
        ])

    table = Table(
        table_data,
        colWidths=[170, 90, 90, 90]
    )

    table.setStyle(
        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#0B6E4F")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BACKGROUND", (0, 1), (-1, -1), HexColor("#F8F8F8")),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

        ])
    )

    elements.append(table)

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "<b>Summary</b>",
            heading_style
        )
    )

    elements.append(Spacer(1, 10))

    summary = []

    for label, key in metrics:

        diff = current[key] - previous[key]

        if diff > 0:
            text = f"{label} increased by {diff}"
        elif diff < 0:
            text = f"{label} decreased by {abs(diff)}"
        else:
            text = f"{label} remained unchanged"

        summary.append(
            Paragraph(f"• {text}", normal_style)
        )

    for line in summary:
        elements.append(line)

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "<font color='grey'>Generated automatically by Sunfra Farm AI Assistant</font>",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            "<font color='grey'>Confidential - Internal Farm Report</font>",
            normal_style
        )
    )

    doc.build(elements)

    return filename

def generate_comparison_pdf_report(
    comparison,
    date1=None,
    date2=None,
    shed_no=None
):

    if comparison == "day":

        result = get_day_comparison(
            compare_date=None,
            shed_no=shed_no
        )

        title = "Today vs Yesterday"

    elif comparison == "custom_day":

        result = get_day_comparison_between_dates(
            date1=date1,
            date2=date2,
            shed_no=shed_no
        )

        if shed_no:

            title = f"Shed {shed_no}: {date1} vs {date2}"

        else:

            title = f"{date1} vs {date2}"

    elif comparison == "week":

        result = get_week_comparison(shed_no)

        title = "This Week vs Last Week"

    elif comparison == "month":

        result = get_month_comparison(shed_no)

        title = "This Month vs Last Month"

    current = result["current"]

    previous = result["previous"]

    report_data = {

        "title": title,

        "shed": shed_no,

        "current": current,

        "previous": previous

    }

    return generate_comparison_pdf(report_data)

def generate_shed_pdf_report(shed_no, period):

    report_title = None
    production_records = []
    feed_records = []

    # ---------------- TODAY ----------------
    if period == "today":

        report_date = date.today().strftime("%Y-%m-%d")

        record = get_shed_daily_summary(
            report_date,
            shed_no
        )

        if record:
            production_records.append(record)


        feed_records = get_all_feeds(
            report_date,
            shed_no=shed_no
        )


        report_title = f"Today's Shed {shed_no} Report"

    # ---------------- YESTERDAY ----------------
    elif period == "yesterday":

        yesterday = (
            date.today() - timedelta(days=1)
        )

        report_date = yesterday.strftime("%Y-%m-%d")


        record = get_shed_daily_summary(
            report_date,
            shed_no
        )


        if record:
            production_records.append(record)


        feed_records = get_all_feeds(
            report_date,
            shed_no=shed_no
        )


        report_title = f"Yesterday's Shed {shed_no} Report"

    # ---------------- WEEK ----------------
    elif period in ["this_week", "last_week"]:


        production_records = get_shed_weekly_summary(
            period,
            shed_no
        )


        today = date.today()

        if period == "last_week":
            this_week_start = (
                today - timedelta(days=today.weekday())
            )
            start_date = (
                this_week_start - timedelta(days=7)
            )
            end_date = (
                this_week_start - timedelta(days=1)
            )

            report_title = (
                f"Last Week Shed {shed_no} Report"
            )
        else:
            start_date = (
                today - timedelta(days=today.weekday())
            )
            end_date = today
            report_title = (
                f"This Week Shed {shed_no} Report"
            )

        feed_records = get_all_feeds(
            start_date,
            end_date,
            shed_no
        )



    # ---------------- MONTH ----------------
    elif period in ["this_month", "last_month"]:


        production_records = get_shed_monthly_summary(
            period,
            shed_no
        )


        today = date.today()


        if period == "last_month":


            first_day = today.replace(day=1)


            end_date = (
                first_day - timedelta(days=1)
            )


            start_date = (
                end_date.replace(day=1)
            )


            report_title = (
                f"Last Month Shed {shed_no} Report"
            )


        else:


            start_date = today.replace(day=1)

            end_date = today


            report_title = (
                f"This Month Shed {shed_no} Report"
            )



        feed_records = get_all_feeds(
            start_date,
            end_date,
            shed_no
        )



    # ---------------- CUSTOM DATE ----------------
    else:


        # Example:
        # 2026-07-11 shed 2 pdf


        report_date = period


        record = get_shed_daily_summary(
            report_date,
            shed_no
        )


        if record:
            production_records.append(record)


        feed_records = get_all_feeds(
            report_date,
            shed_no=shed_no
        )


        report_title = (
            f"Shed {shed_no} Report ({report_date})"
        )



    # ---------------- COMMON DATA ----------------

    medicine_records = get_all_medicines()


    feed_totals = get_feed_totals_kg()


    medicine_totals = get_medicine_totals_kg()



    report_data = {


        "report_date": report_title,


        "production_records": production_records,


        "feed_records": feed_records,


        "medicine_records": medicine_records,


        "production_totals": {},


        "feed_totals": feed_totals,


        "medicine_totals": medicine_totals,


        "pending_reports": []

    }



    return generate_weekly_pdf(report_data)

